spring:
  application:
    name: spring-migration-AI-api

  ai:
    openai:
      api-key: ${OPENAI_API_KEY} # Variable de entorno
      chat:
        options:
          model: gpt-4o-mini          # Modelo
          temperature: 0.5              # Ajusta la creatividad

